config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats, only: [:index, :show, :new, :create, :delete]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(set_params)
    if @flat.save
      redirect_to flats_path
    else
      render :new
    end
  end

  private

  def set_params
    params.require(:flat).permit(:name, :address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<nav class="navbar navbar-light bg-dark">
  <span class="navbar-brand mb-0 h1">Navbar</span>
  <%= link_to 'Add Flat', new_flat_path %>
</nav>
<h1>All our Flats (4)</h1>
<div class="container mt-5">
  <% @flats.each do |flat| %>
    <div class="card">
      <h2 class="card-title"><%= flat.name %></h2>
      <p><%= flat.address %></p>
      <div class="icons">
        <div class="flex">
        <i class="fas fa-users"></i>
        <span><%= flat.number_of_guests %></span>
        </div>
        <div class="flex">
        <i class="fas fa-euro-sign"></i>
        <span><%= flat.price_per_night %></span>
        </div>
      </div>
      <hr>
      <%= link_to 'More info', flat_path(flat) %>
      <%= link_to 'Edit', flat_path(flat) %>
      <%= link_to 'Remove', flat_path(flat) %>
    </div>
   <% end %>
</div>

app/views/flats/new.html.erb
<div class="container mt-5">
<%= simple_form_for(@flat) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.button :submit, "Add Flat", class:"btn btn-primary"%>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>